### ISSUE TITLE
How old are these keys viz isn't working

### ISSUE THREAD

**Issue by maphew** [breck7/keyboard#1]
The visualization at https://breckyunits.com/keyboard/# doesn't do anything in FF and Chrome on Win11.

Clicking on keyboard buttons makes them depress for a moment but that's the only visual interaction. Everything under the [Controls] heading have no apparent result.

Aside form that, thanks for the post at https://breckyunits.com/how-old-are-these-keys.html. Thought provoking.

Web developer console reports:

>jquery-3.4.1.min.js:4 Uncaught SyntaxError: Cannot use import statement outside a module (at jquery-3.4.1.min.js:4:1)
>jtree.browser.js:6918 Uncaught SyntaxError: Cannot use import statement outside a module (at jtree.browser.js:6918:1)
>keyboard.browser.js:202 Uncaught SyntaxError: Cannot use import statement outside a module (at keyboard.browser.js:202:1)
>keyboard.js:111 Uncaught SyntaxError: Cannot use import statement outside a module (at keyboard.js:111:1)

**Comment by breck7** [comment]
Sorry @maphew ! I have no way to test on Win11. Is there a quick way I can use Win11 online?

Here's how it works on my macbook:
![2023-02-17 12 44 39](https://user-images.githubusercontent.com/74692/219789775-5e587bfa-8fe1-401c-815a-5c5277197f20.gif)

**Comment by maphew** [comment]
Thanks for video. That's very interesting. 
Unfortunately I'm not aware of any way to test or use Windows online.
